SS/SS/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SS.Models;

namespace SS.Controllers
{
    public class RoomController : Controller
    {
        private SSSSContext db = new SSSSContext();

        //
        // GET: /Room/

        [Authorize]
        public ActionResult Index()
        {
            return View(db.Room.ToList());
        }

        //
        // GET: /Room/Details/5

        [Authorize]
        public ActionResult Details(int id = 0)
        {
            Room room = db.Room.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            return View(room);
        }

        //
        // GET: /Room/Create

        [Authorize]
        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView("_CreateRoom");
            }
            else
            {
                return View();
            }
        }

        //
        // POST: /Room/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Room room)
        {
            if (ModelState.IsValid)
            {
                room.RoomName = room.Building + " " + room.RoomNumber;
                db.Room.Add(room);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(room);
        }

        //
        // GET: /Room/Edit/5

        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            Room room = db.Room.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("_EditRoom", room);
            }
            else
            {
                return View(room);
            }
        }

        //
        // POST: /Room/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Room room)
        {
            if (ModelState.IsValid)
            {
                room.RoomName = room.Building + " " + room.RoomNumber;
                db.Entry(room).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(room);
        }

        //
        // GET: /Room/Delete/5

        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Room room = db.Room.Find(id);
            if (room == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("_DeleteRoom", room);
            }
            else
            {
                return View(room);
            }
        }

        //
        // POST: /Room/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Room room = db.Room.Find(id);
            db.Room.Remove(room);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SS/SS/Controllers/RuleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SS.Models;

namespace SS.Controllers
{
    public class RuleController : Controller
    {
        private SSSSContext db = new SSSSContext();

        //
        // GET: /Rule/

        [Authorize]
        public ActionResult Index()
        {
            var rule = db.Rule.Include(c => c.RuleFor).Include(c => c.RoomTaughtIn).Include(c => c.MustBeTaughtBy);
            return View(rule.ToList());
        }

        //
        // GET: /Rule/Details/5

        [Authorize]
        public ActionResult Details(int id = 0)
        {
            CourseRule courserule = db.Rule.Find(id);
            if (courserule == null)
            {
                return HttpNotFound();
            }
            return View(courserule);
        }

        //
        // GET: /Rule/Create

        [Authorize]
        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName");
                ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName");
                ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName");
                return PartialView("_CreateRule");
            }
            else
            {
                ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName");
                ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName");
                ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName");
                return View();
            }
        }

        //
        // POST: /Rule/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseRule courserule)
        {
            if (ModelState.IsValid)
            {
                db.Rule.Add(courserule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", courserule.CourseId);
            ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName", courserule.RoomId);
            ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName", courserule.InstructorId);
            return View(courserule);
        }

        //
        // GET: /Rule/Edit/5

        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            CourseRule courserule = db.Rule.Find(id);
            if (courserule == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {
                ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", courserule.CourseId);
                ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName", courserule.RoomId);
                ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName", courserule.InstructorId);
                return PartialView("_EditRule", courserule);
            }
            else
            {
                ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", courserule.CourseId);
                ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName", courserule.RoomId);
                ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName", courserule.InstructorId);
                return View(courserule);
            }
        }

        //
        // POST: /Rule/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CourseRule courserule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courserule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", courserule.CourseId);
            ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName", courserule.RoomId);
            ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName", courserule.InstructorId);
            return View(courserule);
        }

        //
        // GET: /Rule/Delete/5

        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            CourseRule courserule = db.Rule.Find(id);
            if (courserule == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("_DeleteRule");
            }
            else
            {
                return View(courserule);
            }
        }

        //
        // POST: /Rule/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CourseRule courserule = db.Rule.Find(id);
            db.Rule.Remove(courserule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SS/SS/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SS.Models;
using System.Web.Helpers;

namespace SS.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class UserController : Controller
    {

        private SSSSContext db = new SSSSContext();

        //
        // GET: /User/

        public ActionResult Index()
        {
            //**ADD ROLES TO DATABASE**
            //RoleModel userrole = new RoleModel();
            //RoleModel adminrole = new RoleModel();
            //userrole.Name = "User";
            //adminrole.Name = "Admin";
            //db.Role.Add(userrole);
            //db.Role.Add(adminrole);
            //db.SaveChanges();

            var user = db.User.Include(u => u.Role);
            return View(user.ToList());
        }

        //
        // GET: /User/Details/5
        //[Authorize(Roles = "Admin")]
        public ActionResult Details(int id = 0)
        {
            UserModel usermodel = db.User.Find(id);
            if (usermodel == null)
            {
                return HttpNotFound();
            }
            return View(usermodel);
        }

        //
        // GET: /User/Edit/5
        //[Authorize(Roles="Admin")]
        public ActionResult ResetPassword(int id = 0)
        {
            UserModel usermodel = db.User.Find(id);
            if (usermodel == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {
                ViewBag.useremail = usermodel.Email;
                ViewBag.userfname = usermodel.FirstName;
                ViewBag.userlname = usermodel.LastName;
                return PartialView("_ResetPassword", usermodel);
            }
            else
            {
                return View(usermodel);
            }
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        public ActionResult ResetPassword(UserModel usermodel)
        {
            if (ModelState.IsValid)
            {
                usermodel.Password = Crypto.HashPassword(usermodel.Password);
                db.Entry(usermodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(usermodel);
        }


        //
        // GET: /User/Create
        //[Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                ViewBag.RoleID = new SelectList(db.Role, "RoleID", "Name");
                return PartialView("_CreateUser");
            }
            else
            {
                ViewBag.RoleID = new SelectList(db.Role, "RoleID", "Name");
                return View();
            }
        }

        //
        // POST: /User/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserModel usermodel)
        {
            if (ModelState.IsValid)
            {
                usermodel.Password = Crypto.HashPassword(usermodel.Password);
                db.User.Add(usermodel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.RoleID = new SelectList(db.Role, "RoleID", "Name", usermodel.RoleID);
            return View(usermodel);
        }

        //
        // GET: /User/Edit/5

        public ActionResult Edit(int id = 0)
        {
            UserModel usermodel = db.User.Find(id);
            if (usermodel == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {
                //ViewBag.RoleID = new SelectList(db.Role, "RoleID", "Name");
                ViewBag.RoleID = new SelectList(db.Role, "RoleID", "Name", usermodel.RoleID);
                ViewBag.Role = usermodel.Role.Name;
                return PartialView("_EditUser", usermodel);
            }
            else
            {
                return View(usermodel);
            }
        }

        //
        // POST: /User/Edit/5
        //[Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserModel usermodel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usermodel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.RoleID = new SelectList(db.Role, "RoleID", "Name", usermodel.RoleID);
            return View(usermodel);
        }

        //
        // GET: /User/Delete/5
        //[Authorize(Roles = "Admin")]
        public ActionResult Delete(int id = 0)
        {
            UserModel usermodel = db.User.Find(id);
            if (usermodel == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {
                return PartialView("_DeleteUser", usermodel);
            }
            else
            {
                return View(usermodel);
            }
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserModel usermodel = db.User.Find(id);
            db.User.Remove(usermodel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

SS/SS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @Scripts.Render("~/bundles/jquery")
    @*<script type="text/javascript" src="~/Scripts/chosen.jquery.js"></script>
    <link rel="stylesheet" href="~/Content/chosen.css" />*@

    <meta charset="utf-8">
    <title>SSSS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
    @Styles.Render("~/Content/bootstrapcss")
    <!-- datatable search, pagination, and stuff -->
    <link rel="stylesheet" type="text/css" href="~/Content/jquery.dataTables.css">

    <link rel="stylesheet" type="text/css" href="~/Content/myCSS.css">
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="/Home">SSSS</a>
                <div id="cssmenu" class="nav-collapse collapse">
                    <ul id="homeTab" class="nav">
                        @if (Request.IsAuthenticated) {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Scheduler", "ViewSchedule", "Semester")</li>
                        }
                        @if (Request.IsAuthenticated) {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" name="manage">Manage<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("Admin"))
                                {
                                <li>@Html.ActionLink("Instructors", "Index", "Instructor")</li>
                                <li>@Html.ActionLink("Courses", "Index","Course")</li>
                                @*<li>@Html.ActionLink("Rules", "Index","Rule")</li>*@
                                <li>@Html.ActionLink("Rooms", "Index", "Room")</li>
                                <li>@Html.ActionLink("Sections", "Index", "Section")</li>
                                <li>@Html.ActionLink("Semesters", "Index", "Semester")</li>
                                <li>@Html.ActionLink("Users", "Index", "User")</li>
                                }
                                else 
                                {
                                <li>@Html.ActionLink("Instructors", "Index", "Instructor")</li>
                                <li>@Html.ActionLink("Courses", "Index","Course")</li>
                                <li>@Html.ActionLink("Rules", "Index","Rule")</li>
                                <li>@Html.ActionLink("Rooms", "Index", "Room")</li>
                                <li>@Html.ActionLink("Sections", "Index", "Section")</li>
                                <li>@Html.ActionLink("Semesters", "Index", "Semester")</li>              
                                }
                            </ul>
                        </li>
                        }
                        @if (Request.IsAuthenticated) {
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                        }
                    </ul>
                    <div class="pull-right">
                        <a> 
                            @Html.Partial("_LoginPartial")
                        </a>
                    </div>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div style ="padding-bottom:20%; padding-left:2%; padding-right:2%; padding-top:.3%;">
        @RenderBody()
    </div>
    <!-- /container -->

    <!-- le javascript
            =======================
            - When using the tinymce.mvc.jquery-package with MVC4, make sure that you moved "@Scripts.Render("~/bundles/jquery")" into the head section.
            placed at the end of the document so the pages load faster -->

    
    

    <!--Make sure that you call this jquery bundle first, if you do not the datatables will not render. -->
    @Scripts.Render("~/bundles/jqueryNew")
    <!-- -->
    <script src="~/Scripts/jquery.dataTables.js"> </script>

    @Scripts.Render("~/bundles/bootstrapjs")
    
    <script src="~/Scripts/myjQuery.js"> </script>
    @*<script src="~/Scripts/bootstrap.min.js"> </script>*@
   
    @RenderSection("scripts", required: false)


</body>
</html>

SS/SS/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @Scripts.Render("~/bundles/jquery")
    @*<script type="text/javascript" src="~/Scripts/chosen.jquery.js"></script>
    <link rel="stylesheet" href="~/Content/chosen.css" />*@

    <meta charset="utf-8">
    <title>SSSS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <style>
        body {
            padding-top: 60px; 
            padding-left: -200px;
            padding-top: -200px;/* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
    @Styles.Render("~/Content/bootstrapcss")
    <link rel="stylesheet" type="text/css" href="~/Content/myCSS.css">
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="brand" href="/Home">SSSS</a>
                <div id="cssmenu" class="nav-collapse collapse">
                    <ul id="homeTab" class="nav">
                        @if (Request.IsAuthenticated) {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Scheduler", "ViewSchedule", "Semester")</li>
                        }
                        @if (Request.IsAuthenticated) {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" name="manage">Manage<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                @if (User.IsInRole("Admin"))
                                {
                                <li>@Html.ActionLink("Instructors", "Index", "Instructor")</li>
                                <li>@Html.ActionLink("Courses", "Index","Course")</li>
                                <li>@Html.ActionLink("Rules", "Index","Rule")</li>
                                <li>@Html.ActionLink("Rooms", "Index", "Room")</li>
                                <li>@Html.ActionLink("Sections", "Index", "Section")</li>
                                <li>@Html.ActionLink("Semesters", "Index", "Semester")</li>
                                <li>@Html.ActionLink("Users", "Index", "User")</li>
                                }
                                else 
                                {
                                <li>@Html.ActionLink("Instructors", "Index", "Instructor")</li>
                                <li>@Html.ActionLink("Courses", "Index","Course")</li>
                                <li>@Html.ActionLink("Rules", "Index","Rule")</li>
                                <li>@Html.ActionLink("Rooms", "Index", "Room")</li>
                                <li>@Html.ActionLink("Sections", "Index", "Section")</li>
                                <li>@Html.ActionLink("Semesters", "Index", "Semester")</li>              
                                }
                            </ul>
                        </li>
                        }
                        @if (Request.IsAuthenticated) {
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                        }
                    </ul>
                    <div class="pull-right">
                        <a> 
                            @Html.Partial("_LoginPartial")
                        </a>
                    </div>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <!-- /container -->

    <!-- le javascript
            =======================
            - When using the tinymce.mvc.jquery-package with MVC4, make sure that you moved "@Scripts.Render("~/bundles/jquery")" into the head section.
            placed at the end of the document so the pages load faster -->

    
    

    <!--Make sure that you call this jquery bundle first, if you do not the datatables will not render. -->
    @Scripts.Render("~/bundles/jqueryNew")
    <!-- -->
    @Scripts.Render("~/bundles/bootstrapjs")
    
    <script src="~/Scripts/myjQuery.js"> </script>
    @*<script src="~/Scripts/bootstrap.min.js"> </script>*@
   
    @RenderSection("scripts", required: false)


</body>
</html>