SS/SS/Controllers/SectionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SS.Models;
using SS.ViewModels;
using SS.Controllers;
using SS.Helpers;
using System.Data.Entity.Infrastructure;

namespace SS.Controllers
{
    public class SectionController : Controller
    {
        private SSSSContext db = new SSSSContext();

        //
        // GET: /Section/

        [Authorize]
        public ActionResult Scheduler(int id)
        {
            List<SectionConflictViewModel> vmList = new List<SectionConflictViewModel>();
            List<Section> sections = db.Section.Where(x => x.SemesterId == id).ToList();
            List<SectionConflict> conflicts = db.SectionConflict.ToList();
            foreach(Section s in sections){
                SectionConflictViewModel tempVM = new SectionConflictViewModel();
                tempVM.sectionConflicts = new List<SectionConflict>();
                tempVM.aSection = s;

                foreach( SectionConflict c in conflicts){
                    if(c.parentSection.SectionId == s.SectionId){
     
                            tempVM.sectionConflicts.Add(c);           
                    }
                }
                vmList.Add(tempVM);
            }
            return View(vmList);
        }

        //
        // GET: /Section/

        [Authorize]
        public ActionResult Index(List<ViewModels.SectionConflictViewModel> sectionVM)
        {
            List<SectionConflictViewModel> vmList = new List<SectionConflictViewModel>();
            List<Section> sections = db.Section.ToList();
            List<SectionConflict> conflicts = db.SectionConflict.ToList();
            foreach(Section s in sections){
                SectionConflictViewModel tempVM = new SectionConflictViewModel();
                tempVM.sectionConflicts = new List<SectionConflict>();
                tempVM.aSection = s;

                foreach( SectionConflict c in conflicts){
                    if(c.parentSection.SectionId == s.SectionId){
     
                            tempVM.sectionConflicts.Add(c);           
                    }
                }
                vmList.Add(tempVM);
            }
            
            //sectionVM.aSection = sections;
            //sectionVM.sectionConflicts = conflicts;         
            return View(vmList);
        }

        //
        // GET: /Section/Details/5

        [Authorize]
        public ActionResult Details(int id = 0)
        {
            Section section = db.Section.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        //
        // GET: /Section/Create

        [Authorize]
        public ActionResult Create()
        {
            if (Request.IsAjaxRequest())
            {
                ViewBag.SemesterId = new SelectList(db.Semester, "SemesterId", "semesterName");
                ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName");
                ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName");
                ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName");
                return PartialView("_CreateSection");
            }
            else
            {
                ViewBag.SemesterId = new SelectList(db.Semester, "SemesterId", "semesterName");
                ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName");
                ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName");
                ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName");
                return View();
            }
        }

        //
        // POST: /Section/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Section section)
        {
            if (ModelState.IsValid)
            {
                SectionsOnInsert.initialize(section, section.SemesterId, db);
                return RedirectToAction("ViewSchedule", "Semester");
            }

            ViewBag.SemesterId = new SelectList(db.Semester, "SemesterId", "semesterName", section.SemesterId);
            ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName", section.RoomId);
            ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", section.CourseId);
            ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName", section.InstructorId);
            return View(section);
        }

        //
        // GET: /Section/Edit/5

        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            Section section = db.Section.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            if (Request.IsAjaxRequest())
            {
                ViewBag.SemesterId = new SelectList(db.Semester, "SemesterId", "semesterName", section.SemesterId);
                ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName", section.RoomId);
                ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", section.CourseId);
                ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName", section.InstructorId);
                return PartialView("_EditSection",section);
            }
            else
            {
                ViewBag.SemesterId = new SelectList(db.Semester, "SemesterId", "semesterName", section.SemesterId);
                ViewBag.RoomId = new SelectList(db.Room, "RoomId", "RoomName", section.RoomId);
                ViewBag.CourseId = new SelectList(db.Course, "CourseId", "CourseName", section.CourseId);
                ViewBag.InstructorId = new SelectList(db.Instructor, "InstructorId", "FullName", section.InstructorId);
                return View(section);
            }
        }

        //
        // POST: /Section/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Section section)
        {
            if (ModelState.IsValid)
            {
                List<Section> semesterSections = db.Section.Where(x => x.SemesterId == section.SemesterId && x.SectionId != section.SectionId).ToList();
                //remove section from list
                //semesterSections.RemoveAll(i => i.SectionId == section.SectionId);
               
                
                
                //((IObjectContextAdapter)db).ObjectContext.Detach(semesterSections);
                RuleChecker.returnWrapper returnWrapperForSection = RuleChecker.initialize(section, section.SemesterId, semesterSections, db);
                //section = returnWrapperForSection.sectionChecked;

                foreach (Section aSection in returnWrapperForSection.listOfSections)
                {
                    if (aSection.SectionId != section.SectionId)
                    {
                        db.Entry(aSection).State = EntityState.Modified;
                    }
                    
                }

                foreach (SectionConflict aConflict in returnWrapperForSection.conflictList)
                {
                    List<SectionConflict> conflictCheck = db.SectionConflict.Where(x => x.parentSection.SectionId == aConflict.parentSection.SectionId && x.sectionConflicted.SectionId == aConflict.sectionConflicted.SectionId).ToList();
                        foreach( SectionConflict c in conflictCheck){
                            if (conflictCheck.Count() > 0 && conflictCheck.Count() <= 1)
                            {
                                c.roomConflict = aConflict.roomConflict;
                                c.instructorConflict = aConflict.instructorConflict;
                                c.cohortConflict = aConflict.cohortConflict;
                                if (c.cohortConflict == false && c.instructorConflict == false && c.roomConflict == false)
                                {
                                    section.HasConflicts = false;
                                }

                                db.Entry(c).State = EntityState.Modified;
                            }
                            if(conflictCheck.Count() == 0)
                            {
                                
                            }
                        }

                        db.SectionConflict.Add(aConflict);
                   
                }
                db.Entry(section).State = EntityState.Modified;
                //db.Section.Add(section);
                
                //DELETE OLD SHIT
                List<SectionConflict> conflicts = db.SectionConflict.Where(x => x.parentSection.SectionId == section.SectionId).ToList();
                List<SectionConflict> conflicts2 = db.SectionConflict.Where(x => x.sectionConflicted.SectionId == section.SectionId).ToList();

                foreach (SectionConflict c in conflicts)
                {
                    List<Section> conflictedSection = db.Section.Where(x => x.SectionId == c.parentSection.SectionId && x.SectionId != section.SectionId).ToList();
                    foreach (Section s in conflictedSection)
                    {
                        s.HasConflicts = false;
                        db.Entry(s).State = EntityState.Modified;
                    }
                    db.SectionConflict.Remove(c);
                }

                foreach (SectionConflict cf in conflicts2)
                {
                    List<Section> conflictedSection2 = db.Section.Where(x => x.SectionId == cf.parentSection.SectionId && x.SectionId != section.SectionId).ToList();

                    foreach (Section s in conflictedSection2)
                    {

SS/SS/Views/Section/Index.cshtml
@model IEnumerable<SS.ViewModels.SectionConflictViewModel>

@{
    ViewBag.Title = "Sections";
}
<script src="jquery.js"></script>
<script src="bootstrap.js"></script>
@*<script type="text/javascript" src="~/Scripts/chosen.jquery.js"></script>
<link rel="stylesheet" href="~/Content/chosen.css" />*@
<script type="text/javascript"> $(document).ready(function () { $('.dropdown-toggle').dropdown(); }); </script>

<h2>Sections</h2>

<p>
    @*<a class="btn btn-primary " href="~/Section/Create" ><i class="icon-plus"></i> New Section </a>*@
    <button class="floatLeft btn btn-primary create-section"><i class="icon-plus"></i> New Section </button>
    <br />
    <br />
</p>

<div id="create-section" class="modal hide fade in">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="createModal" align="center">New Section</h3>
    </div>
    <div id="create-section-container"></div>
</div>

<div id="edit-section" class="modal hide fade in">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="EditModal" align="center">Edit Section</h3>
    </div>
    <div id="edit-section-container"></div>
</div>

<div id="delete-section" class="modal hide fade in">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="DeleteModal" align="center">Delete Section</h3>
    </div>
    <div id="delete-section-container"></div>
</div>

<table id="myDatatable" class="table table-hover tbody table-striped" style="margin-bottom:15px;">
    <thead>
        <tr>
            <th>
                Course
            </th>
            <th>
                Instructor
            </th>
            <th>
                Start/End
            </th>
            <th>
                Room
            </th>
            <th>
                Days Taught
            </th>
            <th>
                Section Number
            </th>
            <th>
                Semester
            </th>
            <th>
                Conflicts
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="SectionId_@item.aSection.SectionId" onclick="clickUnhighlightRow('SectionId_@item.aSection.SectionId')">
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.SectionCourse.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.TaughtBy.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.StartTime) - @Html.DisplayFor(modelItem => item.aSection.EndTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.TaughtInRoom.RoomName)
                </td>
                <td>
                    @if (item.aSection.Monday.Equals(true))
                    {    
                        <a class="label label-success">Mon</a>
                             
                    }
                    @if (item.aSection.Tuesday.Equals(true))
                    {    
                        <a class="label label-success">Tues</a>     
                    }
                    @if (item.aSection.Wednesday.Equals(true))
                    {    
                        <a class="label label-success">Wed</a>     
                    }
                    @if (item.aSection.Thursday.Equals(true))
                    {    
                        <a class="label label-success">Thurs</a>     
                    }
                    @if (item.aSection.Friday.Equals(true))
                    {    
                        <a class="label label-success">Fri</a>     
                    }
                    @if (item.aSection.Monday.Equals(false) && item.aSection.Tuesday.Equals(false) && item.aSection.Wednesday.Equals(false) && item.aSection.Thursday.Equals(false) && item.aSection.Friday.Equals(false))
                    {    
                        <a class="label label-info">Online</a>     
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.SectionNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.SemesterTaughtIn.semesterName)
                </td>
                <td>
                 @if (item.aSection.HasConflicts == false)
                 {
                     <a class="label label-success">No Conflicts</a> 
                 }

                 @if (item.aSection.HasConflicts == true)
                 {  
                        <div class="btn-group">x
                            <button type="button" class="btn btn-mini btn-warning dropdown-toggle" data-toggle="dropdown">
                            Conflicts <span class="caret"></span>
                          </button>

                          <ul class="dropdown-menu" role="menu">

                           @foreach (var conflict in item.sectionConflicts)
                           {
                               if (conflict.roomConflict == false && conflict.instructorConflict == false && conflict.roomConflict == false)
                               {

                               }

                               else
                               {
                                    <li class="SectionId_@conflict.sectionConflicted.SectionId" onclick="clickHighlightRow('SectionId_@conflict.sectionConflicted.SectionId')" ><a href="#">  <span class="label label-inverse select">@conflict.sectionConflicted.SectionCourse.CourseName Section @conflict.sectionConflicted.SectionNumber</span></a></li>
                                    <li><a href="#">  @if (conflict.instructorConflict.Equals(true))
                                                      {    
                                                         <span class="label label-warning">Instructor Conflict</span>     
                                                      }
                                    </a></li>
                                    <li><a href="#">  @if (conflict.roomConflict.Equals(true))
                                                      {    
                                                         <span class="label label-warning">Room Conflict</span>     
                                                      }
                                    </a></li>
                                    <li><a href="#">  @if (conflict.cohortConflict.Equals(true))
                                                      {    
                                                         <span class="label label-warning">Cohort Conflict</span>     
                                                      }
                                    </a></li>  
                               }

                           }
                          </ul>
                        </div>
                 }
                </td>
                
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.aSection.SectionId }, new { @class = "btn btn-mini edit-section" })@Html.Raw(" | ")*@
                    <button class="@("edit" + item.aSection.SectionId) btn btn-mini edit-section">Edit</button>@Html.Raw(" | ")
                    <script>
                            $('.@("edit" + item.aSection.SectionId)').click(function () {

                                $('#edit-section-container').load("@Url.Action("Edit", "Section", new { id = item.aSection.SectionId })");
                                $('#edit-section').modal('show');
                            });
                    </script>
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.aSection.SectionId }, new { @class = "btn btn-mini btn-danger delete-section" })*@
                    <button class="@("delete" + item.aSection.SectionId) btn btn-mini btn-danger delete-section">Delete</button>
                    <script>
                            $('.@("delete" + item.aSection.SectionId)').click(function () {

                                $('#delete-section-container').load("@Url.Action("Delete", "Section", new { id = item.aSection.SectionId })");
                                $('#delete-section').modal('show');
                            });
                    </script>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{ 
    <script type="text/javascript">
        $(document).ready(function () {
            /* Initialise the DataTable */
            var oTable = $('#myDatatable').dataTable({
                "iDisplayLength": 25,
                "oLanguage": {
                    "sSearch": "",
                    "sInfo": "Showing <b>_START_</b>-<b>_END_</b> out of <b>_TOTAL_</b> records",
                    "sLengthMenu": 'Display <select>' +
                       '<option value="10">10</option>' +
                       '<option value="25">25</option>' +
                       '<option value="50">50</option>' +
                       '<option value="100">100</option>' +
                       '<option value="-1">All</option>' +
                       '</select> records'
                }
            });

            $('.create-section').click(function () {
                $('#create-section-container').load("@Url.Action("Create")" );
                $('#create-section').modal('show');
            });
        });
    </script>

    <script>
        function highlightRow(classname) {
            //alert(classname);
            var row = document.getElementById(classname);
            row.style.backgroundColor = "pink";
        }   

        function unHighlightRow(classname) {
            //alert(classname);
            var row = document.getElementById(classname);
            row.style.backgroundColor = "";
        }

        function clickHighlightRow(classname) {
            //alert(classname);
            var row = document.getElementById(classname);
            row.style.backgroundColor = "pink";
        }

        function clickUnhighlightRow(classname) {
            //alert(classname);
            var row = document.getElementById(classname);
            row.style.backgroundColor = "";
        }

    </script>
}

SS/SS/Views/Section/Scheduler.cshtml
@model IEnumerable<SS.ViewModels.SectionConflictViewModel>

@{
    ViewBag.Title = "Scheduler";
    Layout = null;
}
<div style="overflow:hidden;">
    @{int count = 0;
    foreach (var item in Model) {
        if(count == 0){
            <h3 class="floatLeft">Sections for @Html.DisplayFor(modelItem => item.aSection.SemesterTaughtIn.semesterName)</h3>
            count++;
        }
    }
    }
</div>

<p>
    @*<a class="btn btn-primary " href="~/Section/Create" ><i class="icon-plus"></i> New Section </a>*@
    <button class="floatLeft btn btn-primary create-section"><i class="icon-plus"></i> New Section </button>
    <br />
    <br />
</p>

<script type="text/javascript"> $(document).ready(function () { $('.dropdown-toggle').dropdown(); }); </script>

<div id="create-section" class="modal hide fade in">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="createModal">New Section</h3>
    </div>
    <div id="create-section-container"></div>
</div>

<div id="edit-section" class="modal hide fade in">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="EditModal">Edit Section</h3>
    </div>
    <div id="edit-section-container"></div>
</div>

<div id="delete-section" class="modal hide fade in">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="DeleteModal">Delete Section</h3>
    </div>
    <div id="delete-section-container"></div>
</div>

<table id="myDatatable" class="table tbody" style="margin-bottom:15px;">
    <thead>
        <tr>
            <th>
                Course
            </th>
            <th>
                Instructor
            </th>
            <th>
                Start/End
            </th>
            <th>
                Room
            </th>
            <th>
                Days Taught
            </th>
            <th>
                Section Number
            </th>
            <th>
                Conflicts
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="SectionId_@item.aSection.SectionId" onclick="clickUnhighlightRow('SectionId_@item.aSection.SectionId')">
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.SectionCourse.CourseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.TaughtBy.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.StartTime) - @Html.DisplayFor(modelItem => item.aSection.EndTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.TaughtInRoom.RoomName)
                </td>
                <td>
                    @if (item.aSection.Monday.Equals(true))
                    {    
                        <a class="label label-success">Mon</a>
                             
                    }
                    @if (item.aSection.Tuesday.Equals(true))
                    {    
                        <a class="label label-success">Tues</a>     
                    }
                    @if (item.aSection.Wednesday.Equals(true))
                    {    
                        <a class="label label-success">Wed</a>     
                    }
                    @if (item.aSection.Thursday.Equals(true))
                    {    
                        <a class="label label-success">Thurs</a>     
                    }
                    @if (item.aSection.Friday.Equals(true))
                    {    
                        <a class="label label-success">Fri</a>     
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.aSection.SectionNumber)
                </td>
                <td>
                 @if (item.aSection.HasConflicts == false)
                 {
                     <a class="label label-success">No Conflicts</a> 
                 }

                 @if (item.aSection.HasConflicts == true)
                 {  
                        <div class="btn-group">x
                            <button type="button" class="btn btn-mini btn-warning dropdown-toggle" data-toggle="dropdown">
                            Conflicts <span class="caret"></span>
                          </button>

                          <ul class="dropdown-menu" role="menu">

                           @foreach (var conflict in item.sectionConflicts)
                           {
                               if (conflict.roomConflict == false && conflict.instructorConflict == false && conflict.roomConflict == false)
                               {

                               }

                               else
                               {
                                    <li class="SectionId_@conflict.sectionConflicted.SectionId" onclick="clickHighlightRow('SectionId_@conflict.sectionConflicted.SectionId')" ><a href="#">  <span class="label label-inverse select">@conflict.sectionConflicted.SectionCourse.CourseName Section @conflict.sectionConflicted.SectionNumber</span></a></li>
                                    <li><a href="#">  @if (conflict.instructorConflict.Equals(true))
                                                      {    
                                                         <span class="label label-warning">Instructor Conflict</span>     
                                                      }
                                    </a></li>
                                    <li><a href="#">  @if (conflict.roomConflict.Equals(true))
                                                      {    
                                                         <span class="label label-warning">Room Conflict</span>     
                                                      }
                                    </a></li>
                                    <li><a href="#">  @if (conflict.cohortConflict.Equals(true))
                                                      {    
                                                         <span class="label label-warning">Cohort Conflict</span>     
                                                      }
                                    </a></li>  
                               }

                           }
                          </ul>
                        </div>
                 }
                </td>
                
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.aSection.SectionId }, new { @class = "btn btn-mini edit-section" })@Html.Raw(" | ")*@
                    <button class="@("edit" + item.aSection.SectionId) btn btn-mini edit-section">Edit</button>@Html.Raw(" | ")
                    <script>
                        $('.@("edit" + item.aSection.SectionId)').click(function () {

                            $('#edit-section-container').load("@Url.Action("Edit", "Section", new { id = item.aSection.SectionId })");
                                $('#edit-section').modal('show');
                            });
                    </script>
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.aSection.SectionId }, new { @class = "btn btn-mini btn-danger delete-section" })*@
                    <button class="@("delete" + item.aSection.SectionId) btn btn-mini btn-danger delete-section">Delete</button>
                    <script>
                        $('.@("delete" + item.aSection.SectionId)').click(function () {

                            $('#delete-section-container').load("@Url.Action("Delete", "Section", new { id = item.aSection.SectionId })");
                                $('#delete-section').modal('show');
                            });
                    </script>
                </td>
            </tr>
        }
    </tbody>
</table>
 <script type="text/javascript">
     $(document).ready(function () {
         /* Initialise the DataTable */
         var oTable = $('#myDatatable').dataTable({
             "iDisplayLength": 25,
             "oLanguage": {
                 "sSearch": "",
                 "sInfo": "Showing <b>_START_</b>-<b>_END_</b> out of <b>_TOTAL_</b> records",
                 "sLengthMenu": 'Display <select>'+
                    '<option value="10">10</option>'+
                    '<option value="25">25</option>'+
                    '<option value="50">50</option>'+
                    '<option value="100">100</option>'+
                    '<option value="-1">All</option>'+
                    '</select> records'
             }
         });

         $('.create-section').click(function () {
             $('#create-section-container').load("@Url.Action("Create")");
                $('#create-section').modal('show');
            });
        });
    </script>

    <script>
        function highlightRow(classname) {
            //alert(classname);
            var row = document.getElementById(classname);
            row.style.backgroundColor = "pink";
        }

        function unHighlightRow(classname) {
            //alert(classname);
            var row = document.getElementById(classname);
            row.style.backgroundColor = "";
        }

        function clickHighlightRow(classname) {
            //alert(classname);
            var row = document.getElementById(classname);
            row.style.backgroundColor = "pink";
        }

        function clickUnhighlightRow(classname) {
            //alert(classname);
            var row = document.getElementById(classname);
            row.style.backgroundColor = "";
        }

    </script>